# -*- coding: utf-8 -*-
"""AbbrevTwoName.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d5DiUaodb909EDbPHLGjShxJraoKS_34
"""

#Write a function to convert a name into initials.
#This kata strictly takes two words with one space in between them.

#The output should be two capital letters with a dot separating them.

def abbrev_name(name):
    lastname = name.index(" ") + 1
    abbrev = name[0] + "." + name[lastname]
    abbrev = abbrev.upper()
    return abbrev