# -*- coding: utf-8 -*-
"""Area-or-Perimeter

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15BliiMzubsM5UdSQAMofHocoVnaC8ps4
"""

#You are given the length and width of a 4-sided polygon.
#The polygon can either be a rectangle or a square.

#If it is a square, return its area.
#If it is a rectangle, return its perimeter.

def area_or_perimeter(l, w):
    return l * w if l == w else 2* (l + w)