# -*- coding: utf-8 -*-
"""CountingSheep.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ylHEzfioG_uEh34A40ROUyi3d-HkiYl1
"""

#Consider an array/list of sheep where some sheep may be missing from their place.
#We need a function that counts the number of sheep present in the array
#(true means present).

def count_sheeps(sheep):
  return sheep.count(True)

array1 = [True,  True,  True,  False,
          True,  True,  True,  True ,
          True,  False, True,  False,
          True,  False, False, True ,
          True,  True,  True,  True ,
          False, False, True,  True ];

count_sheeps(array1)

