# -*- coding: utf-8 -*-
"""MiddleCharacter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iBiOMs1uaW0JSfFlCu_qnLThUwKbvUAa
"""

#You are going to be given a word. Your job is to return the middle character of the word.
#If the word's length is odd, return the middle character. If the word's length is even, return the middle 2 characters.

def get_middle(s):
    mid=int(len(s) / 2)
    if len(s)%2==0:
        return s[mid-1:mid+1]
    else:
        return s[mid]

get_middle("abcef")