# -*- coding: utf-8 -*-
"""PositiveArray.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XNRWxXjX8VFO1ahAIAtQkDirHk7Gv10d
"""

#You get an array of numbers, return the sum of all of the positives ones.

#Example [1,-4,7,12] => 1 + 7 + 12 = 20

#Note: if there is nothing to sum, the sum is default to 0.

def positive_sum(arr):
    x = 0
    sum = 0
    for x in arr:
        if x >0:
            sum += x
    return sum