# -*- coding: utf-8 -*-
"""RemoveCharacters

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1geZ8lVdgSdt87vfbipPoIqcB852OX8kq
"""

#It's pretty straightforward.

#Your goal is to create a function that removes the first and last characters of a string.

#You're given one parameter, the original string.

#You don't have to worry with strings with less than two characters.

def remove_char(s):
    s = s[1:-1]
    return s
    #your code here