# -*- coding: utf-8 -*-
"""SchoolPaperwork

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mTHSbM5CxW6afKVI6zUoRSBcM2LPTURl
"""

#Your classmates asked you to copy some paperwork for them.
#You know that there are 'n' classmates and the paperwork has 'm' pages.

#Your task is to calculate how many blank pages do you need. If n < 0 or m < 0 return 0.

def paperwork(n, m):
    if n>0 and m>0:
        return n * m
    else:
        return 0